src/Entity/Agence.php
<?php

namespace App\Entity;

use App\Repository\AgenceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AgenceRepository::class)]
class Agence
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $local = null;

    /**
     * @var Collection<int, Agence>
     */
    #[ORM\OneToMany(targetEntity: Agence::class, mappedBy: 'annonce')]
    private Collection $agences;

    public function __construct()
    {
        $this->agences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getLocal(): ?string
    {
        return $this->local;
    }

    public function setLocal(string $local): static
    {
        $this->local = $local;

        return $this;
    }

    /**
     * @return Collection<int, Agence>
     */
    public function getAgences(): Collection
    {
        return $this->agences;
    }

    public function addAgence(Agence $agence): static
    {
        if (!$this->agences->contains($agence)) {
            $this->agences->add($agence);
            $agence->setAnnonce($this);
        }

        return $this;
    }

    public function removeAgence(Agence $agence): static
    {
        if ($this->agences->removeElement($agence)) {
            // set the owning side to null (unless already changed)
            if ($agence->getAnnonce() === $this) {
                $agence->setAnnonce(null);
            }
        }

        return $this;
    }
}

src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnnonceRepository::class)]
class Annonce
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\Column]
    private ?int $nbr_like = null;

    #[ORM\ManyToOne(inversedBy: 'agences')]
    private ? Annonce $annonce = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getNbrLike(): ?int
    {
        return $this->nbr_like;
    }

    public function setNbrLike(int $nbr_like): static
    {
        $this->nbr_like = $nbr_like;

        return $this;
    }
}

src/Controller/AgenceController.php
<?php

namespace App\Controller;

use App\Entity\Agence;
use App\Repository\AgenceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/crud/agence')]
class CrudAgenceController extends AbstractController
{
    #[Route('/list', name: 'app_crud_agence')]
    public function listAgence(AgenceRepository $repository): Response
    {
        $agences = $repository->findAll();
        return $this->render('agence/listAgence.html', ['agences' => $agences]);
    }

    #[Route('/search', name: 'app_search_agence')]
    public function searchByName(Request $request, AgenceRepository $repository): Response
    {
        $name = $request->query->get('name');
        $agences = $repository->findBy(['name' => $name]);
        return $this->render('agence/listAgence.html', ['agences' => $agences]);
    }

    #[Route('/insert', name: 'app_insert_agence')]
    public function insertAgence(ManagerRegistry $doctrine): Response
    {
        $agence = new Agence();
        $agence->setName('Agence ');
        $agence->setLocal('Localisation ');

        $em = $doctrine->getManager();
        $em->persist($agence);
        $em->flush();

        return $this->redirectToRoute('app_crud_agence');
    }

    #[Route('/delete/{id}', name: 'app_delete_agence')]
    public function deleteAgence($id, AgenceRepository $repository, ManagerRegistry $doctrine): Response
    {
        $agence = $repository->find($id);
        $em = $doctrine->getManager();
        $em->remove($agence);
        $em->flush();

        return $this->redirectToRoute('app_crud_agence');
    }

    #[Route('/update/{id}', name: 'app_update_agence')]
    public function updateAgence(Agence $agence, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $agence->setLocal('Nouvelle Localisation');
        $em->flush();

        return $this->redirectToRoute('app_crud_agence');
    }
}

src/Controller/AnnonceController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Repository\AnnonceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/crud/annonce')]
class CrudAnnonceController extends AbstractController
{
    #[Route('/list', name: 'app_crud_annonce')]
    public function listAnnonce(AnnonceRepository $repository): Response
    {
        $annonces = $repository->findAll();
        return $this->render('crud_annonce/annonce.html.twig', ['annonces' => $annonces]);
    }

    #[Route('/search', name: 'app_search_annonce')]
    public function searchByTitle(Request $request, AnnonceRepository $repository): Response
    {
        $title = $request->query->get('title');
        $annonces = $repository->findBy(['title' => $title]);
        return $this->render('crud_annonce/annonce.html.twig', ['annonces' => $annonces]);
    }

    #[Route('/insert', name: 'app_insert_annonce')]
    public function insertAnnonce(ManagerRegistry $doctrine): Response
    {
        $annonce = new Annonce();
        $annonce->setTitle('Annonce Exemple');
        $annonce->setPublicationDate(new \DateTime());
        $annonce->setNbrLike(0);

        $em = $doctrine->getManager();
        $em->persist($annonce);
        $em->flush();

        return $this->redirectToRoute('app_crud_annonce');
    }

    #[Route('/delete/{id}', name: 'app_delete_annonce')]
    public function deleteAnnonce($id, AnnonceRepository $repository, ManagerRegistry $doctrine): Response
    {
        $annonce = $repository->find($id);
        $em = $doctrine->getManager();
        $em->remove($annonce);
        $em->flush();

        return $this->redirectToRoute('app_crud_annonce');
    }

    #[Route('/update/{id}', name: 'app_update_annonce')]
    public function updateAnnonce(Annonce $annonce, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $annonce->setNbrLike($annonce->getNbrLike() + 1);
        $em->flush();

        return $this->redirectToRoute('app_crud_annonce');
    }
    #[Route('/{id}/annonces', name: 'app_agence_annonces')]
    public function showAnnonces(Agence $agence): Response
    {
        $annonces = $agence->getAnnonces();

        return $this->render('crud_agence/annonce.html.twig', [
            'annonces' => $annonces,
            'agence' => $agence,
        ]);
    }
}

templates/agence/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AgenceController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/Users/User/Desktop/symfony/test2/src/Controller/AgenceController.php</code></li>
        <li>Your template at <code>C:/Users/User/Desktop/symfony/test2/templates/agence/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/annonce/annonce.html.twig
<html>
<head>
</head>
<body>
<h1>Table of Annonce</h1>
<h1>Liste des annonces pour l'agence {{ agence.name }}</h1>
<form>
    <table>
        <thead>
            <tr><th>ID</th><th>Title</th><th>Publication Date</th><th>Likes</th></tr>
        </thead>
        <tbody>
            {% for annonce in annonces %}
                <tr>
                    <td>{{ annonce.id }}</td>
                    <td>{{ annonce.title }}</td>
                    <td>{{ annonce.publicationDate|date('d/m/Y') }}</td>
                    <td>{{ annonce.nbrLike }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</form>
</body>
</html>

templates/annonce/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AnnonceController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/Users/User/Desktop/symfony/test2/src/Controller/AnnonceController.php</code></li>
        <li>Your template at <code>C:/Users/User/Desktop/symfony/test2/templates/annonce/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>